app:
  name: pm-f2f-demo
  namespace: tqvarnst
  virtualMachineName: quarkus-dev
  virtualMachineNamespace: test1
  cluster:    #

build:
  native: false

git:
  branch: main
  repo: github.com
  org: tqvarnst
  name: pm-f2f-demo

image:
  url: quay.io/tqvarnst/quarkus-rest
  registry:  # NOT USED
  organization:  # NOT USED
  name:  # NOT USED